### ISSUE TITLE
parentK may not have children

### ISSUE THREAD

**Issue by manotoor** [cytoscape/cytoscape.js-klay#11]
https://github.com/cytoscape/cytoscape.js-klay/blob/5a11eb130c8c989bf58e975604f908f54875e02d/src/layout.js#L181

when using this in conjunction with https://github.com/iVis-at-Bilkent/cytoscape.js-expand-collapse

parentK may be undefined, should add a check to see if parentK is defined

**Comment by asiftasleem** [comment]
@manotoor Feel free to create a PR.
