### ISSUE TITLE
Layout doesn't work with nested compound nodes

### ISSUE THREAD

**Issue by ortega2247** [cytoscape/cytoscape.js-klay#12]
I am not sure if this is intended to work or not, but when nested nodes are present it seems that the layout doesn't work. Here is a JS bin to reproduce the behavior: https://jsbin.com/peharelebe/edit?html,css,js,output

**Comment by deztopia** [comment]
I'm having the same problem. Multiple compound nodes are simply rendered on top of each other. Spent a ton of time tweaking the cryptic knobs and levers as well, to no avail.

**Comment by gulian** [comment]
Hi @maxkfranz, 

Any ideas on this one ? On which side do you think there's an issue ? Cytoscape ? Klay ? This plugin ?

Thanks for your help,

Gulian

**Comment by maxkfranz** [comment]
I don’t know offhand. If anyone discovers something, please post here.

**Comment by itf** [comment]
I've submited a fix to the issue: https://github.com/cytoscape/cytoscape.js-klay/pull/21.
