### ISSUE TITLE
ERROR TypeError: Cannot read property 'layout' of undefined at a.Layout.run (cytoscape-klay.js:312)

### ISSUE THREAD

**Issue by TianrenWang** [cytoscape/cytoscape.js-klay#13]
I am having the exact same issue as https://github.com/cytoscape/cytoscape.js-klay/issues/8 even in the newer version that has the webpack.

```
GraphComponent.html:2 ERROR TypeError: Cannot read property 'layout' of undefined
    at a.Layout.run (cytoscape-klay.js:312)
    at cytoscape.min.js:23
    at cytoscape.min.js:23
    at cytoscape.min.js:23
    at new qa (cytoscape.min.js:23)
    at zs (cytoscape.min.js:23)
    at NgCytoComponent.push../src/app/ng-cyto/ng-cyto.component.ts.NgCytoComponent.render (ng-cyto.component.ts:94)
    at NgCytoComponent.push../src/app/ng-cyto/ng-cyto.component.ts.NgCytoComponent.ngOnChanges (ng-cyto.component.ts:87)
    at checkAndUpdateDirectiveInline (core.js:21996)
    at checkAndUpdateNodeInline (core.js:23264)
```

I am running this on Angular CLI environment forked from https://github.com/asiftasleem/angular-2-cytoscape. To replicate this, do all the cytoscape-klay import changes, and then in the ng-cyto.component.ts file add `declare var cytoscapeKlay: any;` to the top, add this below the constructor:

```
ngOnInit() {
        cytoscapeKlay(cytoscape)
}
```

and then change the layout declaration in graph.component.ts to use klay:

```
layout = {
     name: 'klay',
     .......
};
```

The problem occurs when cytoscape is trying to make use of klay in:

```
let cy = cytoscape({
            container : cy_contianer,
            layout: this.layout,
            minZoom: this.zoom.min,
            maxZoom: this.zoom.max,
            style: this.style,
            elements: this.elements,
        });
```

**Comment by dwendt** [comment]
had this issue as well, and this is caused by klay.js not being loaded, which this depends on.

from demo.html:
```
<script src="https://unpkg.com/klayjs@0.4.1/klay.js"></script>
```
