### ISSUE TITLE
Order of Nodes

### ISSUE THREAD

**Issue by keckelt** [cytoscape/cytoscape.js-klay#14]
Hi!
Can i influence the order of the nodes?

I made an [example on codepen](https://codepen.io/keckelt/pen/dBOMxG), where I dynamically add nodes to Cytoscape and would like to have the nodes in the same order (or alphabetical by id) as they are in the data array.
Right now the node placement seems very random.

Is that possible? The Dagre layout on the right seems to do it that way.

I fiddled with the options listed in the README but without success.

**Comment by Wkasel** [comment]
any luck on this?

**Comment by keckelt** [comment]
@Wkasel No, but I didn't look into the code, just the available options.

**Comment by hackey9** [comment]
up!!!
some ideas?

**Comment by Ciappone** [comment]
Hi, someone got a solution for this?

**Comment by alifdoll** [comment]
anyone got a solution for this??

**Comment by Ciappone** [comment]
I don't know if it can be useful...
to get the nodes positioned alphabetically i used [grid layout](https://js.cytoscape.org/#layouts/grid) using it's sort function
