### ISSUE TITLE
NodeLayering Interactive

### ISSUE THREAD

**Issue by mattia85** [cytoscape/cytoscape.js-klay#28]
Hi,
this's not an issue but i need more information about _nodeLayering_ **interactive**.
According with the documentation, the interactive layering should places nodes respecting the original positions of the node,   so I added the initial position to each nodes but seems that this is ignored after running the layout.
Could you please explain me how tell to the layout the initial position of the nodes?

This is my configuration

```javascript 
layoutOptions = {
    name: 'klay',
    padding: 50,
    animate: true,
    klay: {
      direction: 'RIGHT',
      nodeLayering: 'INTERACTIVE',
      nodePlacement: 'SIMPLE',
      compactComponents: true,
    },
  };
```
Thank you.
Mattia

**Comment by maxkfranz** [comment]
This is just a wrapper to Klay.  If you have questions or feedback about the Klay algorithm, you're welcome to get in touch with the authors of Klay and report back here.

Good luck with your project
