### ISSUE TITLE
Upgrade to Klay successor

### ISSUE THREAD

**Issue by d2fong** [cytoscape/cytoscape.js-klay#6]
Seems like they have released a successor for Klay called ELK

https://github.com/OpenKieler/elkjs

**Comment by maxkfranz** [comment]
Probably as a separate extension

**Comment by jfstephe** [comment]
Does anyone know if elkjs works with cytoscape? If so can you offer any clues as to how? I can't find a cytoscape extension for it but I'm new to this world so not sure if they are always needed.

Any ideas/suggestions/examples would be gratefully received! :-)

**Comment by maxkfranz** [comment]
You could use it without an extension, but it would be the same amount of work as creating an extension that would be re-usable and would take advantage of a tighter integration with the Cytoscape.js API.

**Comment by jfstephe** [comment]
thanks for the tips! :-)

**Comment by maxkfranz** [comment]
@jfstephe has created an extension: https://github.com/jfstephe/cytoscape.js-elk
