### ISSUE TITLE
Cannot read property 'layout' of undefined

### ISSUE THREAD

**Issue by pmackay** [cytoscape/cytoscape.js-klay#8]
I get this error when running this layout:

```
Uncaught TypeError: Cannot read property 'layout' of undefined
    at Layout.run (cytoscape-klay.js?a54c:299)
```
Its failing on [this line](https://github.com/cytoscape/cytoscape.js-klay/blob/master/src/layout.js#L228).

**Comment by maxkfranz** [comment]
Please post a reproducible test case

Maybe it's an issue with your build system, in which case you could try building off of master (wip) to see if the new scaffolding (webpack now v.s. browserify before) resolves your issue.

**Comment by pmackay** [comment]
Yes the new scaffolding has resolved it if I build off master. Thanks!

**Comment by TianrenWang** [comment]
I am having the exact same issue even in the newer version that has the webpack.

```
GraphComponent.html:2 ERROR TypeError: Cannot read property 'layout' of undefined
    at a.Layout.run (cytoscape-klay.js:312)
    at cytoscape.min.js:23
    at cytoscape.min.js:23
    at cytoscape.min.js:23
    at new qa (cytoscape.min.js:23)
    at zs (cytoscape.min.js:23)
    at NgCytoComponent.push../src/app/ng-cyto/ng-cyto.component.ts.NgCytoComponent.render (ng-cyto.component.ts:94)
    at NgCytoComponent.push../src/app/ng-cyto/ng-cyto.component.ts.NgCytoComponent.ngOnChanges (ng-cyto.component.ts:87)
    at checkAndUpdateDirectiveInline (core.js:21996)
    at checkAndUpdateNodeInline (core.js:23264)
```

I am running this on Angular CLI environment forked from https://github.com/asiftasleem/angular-2-cytoscape. To replicate this do all the cytoscape-klay import changes, and then in the ng-cyto.component.ts file add `declare var cytoscapeKlay: any;` to the top, add this below the constructor:

```
ngOnInit() {
        cytoscapeKlay(cytoscape)
}
```
and then change the layout declaration in graph.component.ts to use klay:

```
layout = {
                name: 'klay',
                .......
};
```

The problem occurs when cytoscape is trying to make use of klay in:

```
let cy = cytoscape({
            container : cy_contianer,
            layout: this.layout, // <- problem statement
            minZoom: this.zoom.min,
            maxZoom: this.zoom.max,
            style: this.style,
            elements: this.elements,
        });
```
