### ISSUE TITLE
Bug: AMD usage Error 

### ISSUE THREAD

**Issue by mafar** [cytoscape/cytoscape.js-klay#9]
When used with AMD/requireJs, cytoscape.js-klay  throws error

**JSFIDDLE:** http://jsfiddle.net/bababalcksheep/4ezxsgjn/

> Uncaught TypeError: Cannot read property 'layout' of undefined
>     at o.Layout.run (cytoscape-klay.js:312)

I found that cytoscape.js-elk is working fine though
https://github.com/jfstephe/cytoscape.js-elk

**Comment by mafar** [comment]
HI any update on this ?

**Comment by maxkfranz** [comment]
The AMD export is set up by webpack.  If you're having problems with it, I suspect you have a config issue.

**Comment by TianrenWang** [comment]
How do we check we have config issue?

**Comment by ahmadawada11** [comment]
i have the same issue any fix for that
